/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kh_rnairlite_RNAirPatchManager */

#ifndef _Included_com_kh_rnairlite_RNAirPatchManager
#define _Included_com_kh_rnairlite_RNAirPatchManager
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_kh_rnairlite_RNAirPatchManager_decompress(JNIEnv *, jobject,
                                                                             jobject);
JNIEXPORT jobject JNICALL Java_com_kh_rnairlite_RNAirPatchManager_patch(JNIEnv *, jobject, jobject,
                                                                        jobject);

#ifdef __cplusplus
}
#endif
#endif
