/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kh_rnairlite_RNAirLiteModule */

#ifndef _Included_com_kh_rnairlite_RNAirLiteModule
#define _Included_com_kh_rnairlite_RNAirLiteModule
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_kh_rnairlite_RNAirLiteModule_decompress(JNIEnv *, jobject);
JNIEXPORT jobject JNICALL Java_com_kh_rnairlite_RNAirLiteModule_patch(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
